default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: chmh_development

test:
  <<: *default
  database: chmh_test

production:
  <<: *default
  database: chmh_production
  username: deployer
  password: <%= ENV['CHMH_DATABASE_PASSWORD'] %>
